name: Frontend Build and Deploy

on:
  push:
    branches:
      - cicd

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Build Frontend
        run: npm run build

      - name: Copy Build Artifacts
        run: |
          cp -r frontend/build/* api/static/
          cp frontend/build/index.html api/templates/index.html
