name: Frontend Build and Deploy

on:
  push:
    branches:
      - cicd

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Build Frontend
        run: npm run build
        env:
          CI: false
      - name: List files
        run : |
          ls ./build/ -lrt
        
      - name: Copy Build Artifacts
        run: |
          rm -rf ../api/static
          mkdir  ../api/static/
          cp -r build/static/* ../api/static/ 
          cp build/index.html ../api/templates/index.html
          git add api/
          git config --local user.email "krishnadutt123@gmail.com"
          git config --local user.name "krishnaduttpanchagnula"
          git commit -m "Upload build to app folder" || true
          git push
