name: Frontend Build and Deploy

on:
  push:
    branches:
      - cicd

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Build Frontend
        run: npm run build

      - name: Copy Build Artifacts
        run: |
          cd frontend
          cp -r build/* ../api/static/
          cp build/index.html ../api/templates/index.html
