name: Frontend Build and Deploy

on:
  push:
    branches:
      - cicd

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Build Frontend
        run: npm run build
        env:
          CI: false
      - name: Remove the old builds
        run: |
             rm -rf ./api/static/*
             rm ./api/templates/index.html

      - name: Copy Build Artifacts
        run: |
          cp -r ./build/* ./api/static/
          cp ./build/index.html ./api/templates/index.html
